services:
  db:
    image: postgres:16
    container_name: salon-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: salon_user
      POSTGRES_PASSWORD: iecdatabase
      POSTGRES_DB: salon_db
    ports:
      - "5432:5432"
    volumes:
      - "salon_pgdata:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4
    container_name: salon-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  salon_pgdata:
