services:
  db:
    image: postgres:16
    container_name: salon-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: salon_user
      POSTGRES_PASSWORD: iecdatabase
      POSTGRES_DB: salon_db
    ports:
      - "5432:5432"
    volumes:
      - "salon_pgdata:/var/lib/postgresql/data"
volumes:
  salon_pgdata: